### ISSUE TITLE
Dependence of other fields

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-reveal#16]
```
include:
 -
  name: my_textarea
  selector: body .text
  filter: true
 -
  name: my_select
  selector: body div
  filter: false
```

It should then fetch all content from them and send everything as an array to the ajax route.

On the ajax route it needs to use the correct filter option.

It needs to send it back as an array.

Then use the correct selector to place the fields.
